version: "3.8"
services:
  ui:
    build:
      context: ./cmd/ui
    networks:
      - app-network
  gateway:
    build:
      context: ./gateway
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - ui
networks:
  app-network:
    driver: bridge
