version: "3.8"
services:
  ui:
    build:
      context: .
      args:
        SERVICE_NAME: "ui"
        PORT: "8080"
    networks:
      - app-network
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  auth:
    build:
      context: .
      args:
        SERVICE_NAME: "auth"
        LIBRARIES: "./pkg/token"
        PORT: "8081"
    networks:
      - app-network
    ports:
      - "8081:8081"
    environment:
      - TOKEN_SECRET=secret
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  gateway:
    build:
      context: ./gateway
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - ui
      - auth

networks:
  app-network:
    driver: bridge
