apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: localhost/auth:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          readinessProbe:                     # Readiness Probe
            httpGet:
              path: /health                  # Path to your health endpoint
              port: 8081                     # Port where the container listens
            initialDelaySeconds: 5           # Delay before the first probe
            periodSeconds: 10                # Probe frequency
            timeoutSeconds: 3                # Timeout for each probe
            failureThreshold: 3              # Number of failed probes before marking not ready
          livenessProbe:                      # Liveness Probe
            httpGet:
              path: /health                  # Path to your health endpoint
              port: 8081                     # Port where the container listens
            initialDelaySeconds: 10          # Delay before the first probe
            periodSeconds: 15                # Probe frequency
            timeoutSeconds: 5                # Timeout for each probe
            failureThreshold: 3              # Number of failed probes before restarting the pod
