apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  labels:
    app: websocket
spec:
  type: ClusterIP
  selector:
    app: websocket
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  sessionAffinity: ClientIP
