apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistent
  labels:
    app: persistent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: persistent
  template:
    metadata:
      labels:
        app: persistent
    spec:
      containers:
        - name: persistent
          image: localhost/persistent:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: GIN_MODE
              value: release
            - name: KAFKA_URL
              value: localhost:9092
            - name: DB_URL # Handle secrets securely (see below)
              value: host=localhost user=postgres password=password dbname=appdb port=5432 sslmode=disable TimeZone=Asia/Dubai
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3