apiVersion: v1
kind: Service
metadata:
  name: persistent
  labels:
    app: persistent
spec:
  type: ClusterIP
  selector:
    app: persistent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  sessionAffinity: ClientIP
